events {
    worker_connections 1024;
}

http {
    upstream nextjs_cluster {
        # 'web' tương ứng với tên service trong docker-compose.yml
        # Khi bạn scale service 'web', Docker DNS sẽ trả về tất cả các IP của các container 'web'
        # Nginx sẽ mặc định cân bằng tải theo thuật toán Round-Robin
        server web:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nextjs_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Forward real client IP
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Increase proxy buffers for large Next.js headers
            proxy_buffer_size          128k;
            proxy_buffers              4 256k;
            proxy_busy_buffers_size    256k;
        }
    }
}
